### ISSUE TITLE
Not able to add, list or delete longer TXT records

### ISSUE THREAD

**Issue by medhi** [mikepultz/netdns2#107]
When working with longer values for DKIM, we need to add a key, which looks like this:

`mail._domainkey IN TXT "v=DKIM1; h=sha256; k=rsa; s=email; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvzP6TuNk4XyanF/tXXoedlJe4oEV2rrRHEfE2ajsAcB2umcRXHDDvWE8aee7QQFG3H9wbHTK6L1iGC5YcEbHUwHZy7UVUFx8QIUCiMJW6pLDWtzSPoFGreAbwdVmFVq7E6gE0Td3qxM5VpL9syaw63n3Hn+h5drhZVLc4Pfe25xFMIgSvn/HU0UHUQvNeHqltip0vSRvl+JZN73Md9S/FPoS+y8+VJCODnacG1/FR9o14ayK7jejyaCsMSes3Xdx80jK4BL2U0egnqMCvkJFKO1ZaIPFXg359xV59b7S+JTMr41ZL8Pp7FK9++6ElveEUwmJCzWVMXJfUTcGijXh5wIDAQAB"`

But the key is not added. We have to "cut it half" like this: 

`mail._domainkey IN TXT "v=DKIM1; h=sha256; k=rsa; s=email; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvzP6TuNk4XyanF/tXXoedlJe4oEV2rrRHEfE2ajsAcB2umcRXHDDvWE8aee7QQFG3H9wbHTK6L1iGC5YcEbHUwHZy7UVUFx8QIUCiMJW6pLDWtzSPoFGreAbwdVmFVq7E6gE0Td3qxM5VpL9syaw63n3Hn+h5drhZVLc4Pfe25xFM" "IgSvn/HU0UHUQvNeHqltip0vSRvl+JZN73Md9S/FPoS+y8+VJCODnacG1/FR9o14ayK7jejyaCsMSes3Xdx80jK4BL2U0egnqMCvkJFKO1ZaIPFXg359xV59b7S+JTMr41ZL8Pp7FK9++6ElveEUwmJCzWVMXJfUTcGijXh5wIDAQAB"`

(see the `" "` in the middle)

Then it is added and works fine. But still, when list DNS, only the first half is shown and also, it is impossible to delete it (obviously because as a delete string I use only the first part).

What am I missing here? I can't find any solutions, even this is commonly used DKIM key.

Thanks a lot!

**Comment by mikepultz** [comment]
Hey @medhi - do you have a sample of what your code looks like?

You should be able to add multiple text values by passing in an array of values- they should then all show up when you look up the record.

If you have a sample of your code, I can test on my side.

Mike

**Comment by medhi** [comment]
It turned out, that the rest of the value is returned in array, so it's possible to retrieve the value by joining the values of the array. Sorry for missing that.
