### ISSUE TITLE
TCP Connections are held open and no graceful way to disconnect them.

### ISSUE THREAD

**Issue by Crim** [mikepultz/netdns2#109]
### Situation Described

**Time 0**
- We create a `Net_DNS2_Resolver` instance, configured to talk to our name server over TCP.

**Time 1**
 - We issue a query to resolve a host name using this instance
 - `Net_DNS2_Resolver` internally opens a new TCP connection to our name server and issues the request.
 - `Net_DNS2_Resolver` returns a response for our query.
 - `Net_DNS2_Resolver` keeps this connection open.

*---- some time elapses ---*

**Time 2**
 - Our *DNS Server*  disconnects the client/socket created above due to inactivity/timeout.

*---- some time elapses ---*

**Time 3**
- We issue another query to resolve a hostname using the same `Net_DNS2_Resolver` instance.
- The library raises a `Net_DNS2_Exception` with code `Net_DNS2_Lookups::E_NS_SOCKET_FAILED` and message `broken pipe` because the connection is no longer valid (the server closed it).

### How to resolve this scenario?
I can think of a few different ways we could improve how NetDns2 handles this situation, I've outlined a few below :)

##### Throw a more specific exception / set a more specific exception code.
Still leave it up to the caller to deal with it, but improving the exception with a more specific code would be ideal as error code `Net_DNS2_Lookups::E_NS_SOCKET_FAILED` is thrown in multiple situations.

##### Provide a method to allow for closing open connections
There doesn't appear to be any way to explicitly ask `Net_DNS2_Resolver` to close its connections.  Providing this would allow us to explicitly close it and avoid the situation if a connection hasn't been used recently.

##### Handle this issue internally to NetDns2
The library could detect that the server has closed the connection and internally re-connect and re-attempt the query.

**Comment by mikepultz** [comment]
Hey @Crim,

Ok- so I assume you have a long(ish) running process? (obviously long enough for it to time out)

The function that generates that exception will clean up the "broken" socket connections- so depending on how you write you code, you can catch that exception, and then just try it again- for example:

```
$resolver = new Net_DNS2_Resolver([ 'nameservers' => [ '8.8.8.8' ] ]);

$resolver->use_tcp = true;

while(1)
{
    try
    {
        $result = $resolver->query('google.com', 'SOA');
        echo $result->answer[0]."\n";

        $result = $resolver->query('google.com', 'MX');
        echo $result->answer[0]."\n";

        $result = $resolver->query('google.com', 'A');
        echo $result->answer[0]."\n";

        $result = $resolver->query('google.com', 'AAAA');
        echo $result->answer[0]."\n";

        $result = $resolver->query('google.com', 'TXT');
        echo $result->answer[0]."\n";

        // ... do some other stuff...
        //
        sleep(3);

    } catch(Net_DNS2_Exception $e)
    {
        echo "\nEXCEPTION, cleaning up and trying again...\n\n";
    }
}
```
The five query requests will all process on the same TCP socket, but the next time it looks, Google has timed out the TCP connection, so it throws the exception. The code that generated the exception already cleaned up the broken socket, so the next time it loops, it'll just re-connect.

Should look something like this:

```
google.com. 47 IN SOA ns1.google.com. dns-admin.google.com. 335271493 900 900 1800 60
google.com. 517 IN MX 30 alt2.aspmx.l.google.com.
google.com. 299 IN A 172.217.4.110
google.com. 299 IN AAAA 2607:f8b0:4009:800:0:0:0:200e
google.com. 299 IN TXT "docusign=05958488-4752-4ef2-95eb-aa7ba8a3bd0e"

EXCEPTION, cleaning up and trying again...

google.com. 32 IN SOA ns1.google.com. dns-admin.google.com. 335271493 900 900 1800 60
google.com. 430 IN MX 50 alt4.aspmx.l.google.com.
google.com. 299 IN A 172.217.4.110
google.com. 299 IN AAAA 2607:f8b0:4009:800:0:0:0:200e
google.com. 299 IN TXT "docusign=1b0a6754-49b1-4db5-8540-d2c12664b289"
```

Also- I just committed some new code now, that adds a few new things; I added a new Net_DNS2::closeSockets() function- so you can do this:

```
$resolver = new Net_DNS2_Resolver([ 'nameservers' => [ '8.8.8.8' ] ]);

// this will create a new socket
$result = $resolver->query('google.com', 'SOA');

// this will re-use the existing socket
$result = $resolver->query('google.com', 'MX');

// this will close all the cached sockets
$resolver->closeSockets();

// this will create a new socket, since all of the cached sockets are closed
$result = $resolver->query('google.com', 'A');

```
This will close all cached sockets on the resolver.

I also added Net_DNS2::getSockets() which returns the list of the cached socket objects, and each socket object now has a "date_created" and "date_last_used" date value (using microtime(true)), which you can use to determine how "old" a cached socket object is, in case you want to call close() on it to shut it down.

```
$resolver = new Net_DNS2_Resolver([ 'nameservers' => [ '8.8.8.8' ] ]);
$resolver->use_tcp = true;
$result = $resolver->query('google.com', 'SOA');

print_r($resolver->getSockets());

```
would return something like:
```
Array
(
    [2] => Array
        (
        )

    [1] => Array
        (
            [8.8.8.8] => Net_DNS2_Socket Object
                (
                    [sock:Net_DNS2_Socket:private] => Resource id #13
                    [type:Net_DNS2_Socket:private] => 1
                    [host:Net_DNS2_Socket:private] => 8.8.8.8
                    [port:Net_DNS2_Socket:private] => 53
                    [timeout:Net_DNS2_Socket:private] => 5
                    [context:Net_DNS2_Socket:private] => Resource id #12
                    [local_host:Net_DNS2_Socket:private] => 
                    [local_port:Net_DNS2_Socket:private] => 
                    [last_error] => 
                    [date_created] => 1601872245.1963
                    [date_last_used] => 1601872245.3249
                )

        )

)
```
I think, with all that, you should be able to solve your issue a few different ways; let me know what you think.

These updated changes will be tagged as v1.5.0 shortly, or just grab master.

Mike

**Comment by Crim** [comment]
Hey Mike!

Thanks for the quick response.  We've been handling this situation with the first method you described, effectively catching the exception, looking for the `broken pipe` message, and if matched re-issuing the request.

These new methods you've added I believe should provide a cleaner way to handle this situation, thanks a bunch!

Stephen

**Comment by Crim** [comment]
Ah this also solves another issue we were having which was getting access to the underlying socket errors when you have more than one server configured.  Fantastic, thanks, really appreciate it.

**Comment by mikepultz** [comment]
No problem at all,

Cheers,

Mike
