### ISSUE TITLE
Exception: failed to fwrite() packet

### ISSUE THREAD

**Issue by rvalitov** [mikepultz/netdns2#114]
Hello! I would like to share my case that may be useful.

I use the following code from the example:
```php
$r = new Net_DNS2_Resolver(array('nameservers' => array('1.1.1.1')));
try {
        $result = $r->query('google.com', 'A');
        
} catch(Net_DNS2_Exception $e) {
        echo $e->getMessage();
}
```

I get the following error:
```
failed to fwrite() packet
```

This error happened only at one hosting, but everything was perfect at another.
I found out, that this error happened because the hosting firewall configuration prohibited using any DNS servers other than its own internal DNS servers. So, even my requests from console also failed:

```console
user@server:~$ nslookup google.com 1.1.1.1
;; connection timed out; no servers could be reached
```

I think this case should be documented in the FAQ or troubleshooting guide.

**Comment by rvalitov** [comment]
Another case. If the firewall does not explicitly reject the connection, but silently drops it, then timeout occurs with exception message `timeout on read select()` and code `203` (`Net_DNS2_Lookups::E_NS_SOCKET_FAILED`).

**Comment by mikepultz** [comment]
Hey @rvalitov 

When you got the fwrite() error, did it fail immediately? or did it hang for a few seconds (a timeout)?

Mike

**Comment by rvalitov** [comment]
Immediately. No delays at all.

**Comment by mikepultz** [comment]
I haven't been able to reproduce this, and there have been no other reports of similar issues.

Closing this case; if it happens again, and we can get more details, then we'll review again.

Mike
