### ISSUE TITLE
In version 1.5.2 we get "PHP Warning:  Undefined array key 65 in /var/www/site/vendor/pear/net_dns2/Net/DNS2/RR.php on line 442"

### ISSUE THREAD

**Issue by SiteProTeam** [mikepultz/netdns2#119]

**Comment by Woet** [comment]
It would be very helpful if you could provide your PHP version and a test case to reproduce this error.

**Comment by SiteProTeam** [comment]
Hello,
Unfortunately, we cannot provide a test case at the moment.
According to https://en.wikipedia.org/wiki/List_of_DNS_record_types, the index 65 stands for "HTTPS binding" DNS record type. Actually, we do not need a support of it. But we think that the issue can still be fixed, at least to prevent PHP warning logging (for example, by adding "isset" checking in RR.php on line 442).

**Comment by mikepultz** [comment]
Will be fixed in v1.5.3
