### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by chaosben** [mikepultz/netdns2#122]
**File:** Socket.php
**Line:** 132
**Code:** `if (strlen($this->local_host) > 0) {`
**Error:** `Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated`

**Comment by cubiclesoft** [comment]
The simple fix is to force an explicit cast to string.  That seems to have fixed the problem for me.

**Comment by chaosben** [comment]
What about all the other internal-function-calls? It seems to me, that a code review is needed.

**Comment by cubiclesoft** [comment]
Sure but I'm not the author of this library.  I just happened to run into the same issue as you while doing an upgrade of a bunch of libraries to PHP 8.1.  I'm sure there's more stuff lurking in this library but this was the one issue I ran into and a simple forced cast might be all someone cares about.  Forced casts tend to make the new deprecations that popped up in PHP 8.1 go away.  Is this notice/warning an indicator of a bug in the library?  Possibly.  I'm not familiar enough with the code to make that determination.

**Comment by chaosben** [comment]
Sorry ... didnt recognized, that you aren't the author. :-)

**Comment by abienvenu** [comment]
There is a pull request waiting to solve this issue : https://github.com/mikepultz/netdns2/pull/121

**Comment by mikepultz** [comment]
Fix will be included in v1.5.3
