### ISSUE TITLE
php 8.1 compatibility

### ISSUE THREAD

**Issue by Pascal76** [mikepultz/netdns2#127]
Hello,

Would you have time to make the code compatible with php 8.1 ?
ex:
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /apache_sites/jbm/lib_8.1/vendor/pear/net_dns2/Net/DNS2/Socket.php on line 132

**Comment by offsky** [comment]
Im just starting to upgrade to PHP 8.1 and found this warning too. The solution is pretty easy.  On line 132 of Socket.php add `!empty($this->local_host)`

**Comment by Jellyfrog** [comment]
Stupid quickfix:

```php
$this->resolver = new \Net_DNS2_Resolver();
// Workaround for strlen() null
// https://github.com/mikepultz/netdns2/blob/master/Net/DNS2/Socket.php#L132
$this->resolver->local_host = "0";
```

**Comment by Blackbam** [comment]
Recognized the same. Merging this would be great.

**Comment by Pascal76** [comment]
php 7.4 EOL is coming very soon (in less than 20 days).
Lot of people will move to php 8.1
It would be great to finalize the compatibility.

**Comment by Blackbam** [comment]
@mikepultz Can you please merge that (see discussion)? Otherwise some people might have to do a fork, although the quickfix works it is not the best solution.

**Comment by Pascal76** [comment]
thank you for the new build !!!

**Comment by Pascal76** [comment]
=)
