### ISSUE TITLE
Wrong result in retrieving TXT records for multi-line records

### ISSUE THREAD

**Issue by JerBlo** [mikepultz/netdns2#131]
From version 1.5.3 some behavior has changed (in 1.5.2 there was no issue) when retrieving a TXT record which consists of multiple parts.

Example from terminal:
`$ dig -t txt domain.com

; <<>> DiG 9.16.1-Ubuntu <<>> -t txt domain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43633
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;domain.com.			IN	TXT

;; ANSWER SECTION:
domain.com.		1279	IN	TXT	"v=spf1 a mx ip4:123.456.78.0/22 ip4:123.456.678.0/21 ip6:1a03:4c00:a001::/48 ip6:1a03:4c00:a002::/48 include:spf.protection.outlook.com include:_spf." "mydomain.nl ~all"`

The problem is that the end result removes the . after _spf, because of the changed line in:
https://github.com/mikepultz/netdns2/compare/v1.5.2...v1.5.3#diff-50018c28008d797b7dec6535f58736fc41dac169b9b1a16ab67437f1558ef170R72

In this case, it's the value of a string which should be concatenated, the dot should not be trimmed here.

Could you re-evaluate the change in Net_DNS2_Names?
Please let me know if you need any additional information.

**Comment by mikepultz** [comment]
Thanks @JerBlo, that's definitely not right.

Update will be included in the next release (probably this weekend).

Mike

**Comment by JerBlo** [comment]
Thanks. Just let me know which commit should fix this issue, i'm happy to check and confirm if it is fixed.

**Comment by JerBlo** [comment]
Hey @mikepultz, do you maybe have an update on this one?
Thanks!
