### ISSUE TITLE
Senseless comparison in Socket->read

### ISSUE THREAD

**Issue by chaosben** [mikepultz/netdns2#133]
It looks it little bit senselsess to me, to comapre $length with false:
https://github.com/mikepultz/netdns2/blob/1284c4b1f0a0e1fe087b4fec7dff960d0527e273/Net/DNS2/Socket.php#L428-L433

Maybe it should look like:
```php
if ($data === false) {
    $this->last_error = 'failed on fread() for data';
    return false;
}
```

**Comment by mikepultz** [comment]
Thanks @chaosben  - looks like a typo; will be included in the next release.

Mike
