### ISSUE TITLE
Endless loop if server answers not as expected

### ISSUE THREAD

**Issue by chaosben** [mikepultz/netdns2#134]
I'm trying an AXFR at 89.252.140.236 (from NS-record) for the domain "googleanalytics.com.org.tr". Because the server answers with an HTTP-Answer (on port 53 🙄), which is shorter than calculated from the first two bytes, the Socket->read loops endless here:

https://github.com/mikepultz/netdns2/blob/1284c4b1f0a0e1fe087b4fec7dff960d0527e273/Net/DNS2/Socket.php#L405-L420

Test-Code:
```php
<?php

require 'vendor/autoload.php';

$resover = new Net_DNS2_Resolver(['nameservers' => ['89.252.140.236']]);
$resover->query('googleanalytics.com.org.tr', 'AXFR');
```
I think a test for EOF should fix it;

```php
while (1) {
    $chunk = fread($this->sock, $chunk_size);
    if ($chunk === false) {
        $this->last_error = 'failed on fread() for data';
        return false;
    }

    $data .= $chunk;
    $chunk_size -= strlen($chunk);

    if ((strlen($data) >= $length) || feof($this->sock)) {  //check for EOF
        break;
    }
}
```

**Comment by mikepultz** [comment]
This library doesn't support HTTP requests- it goes way deeper than checking for a EOF- it's a completely different protocol.

I'm not sure what standard that endpoint supports, but if it's RFC 8484 or JSON API - i'd suggest using CURL.

**Comment by chaosben** [comment]
The mentioned name server is simply configured incorrectly. And since this could theoretically occur with any nameserver, testing for EOF would be very helpful.
