### ISSUE TITLE
php 8.2 compatibility ?

### ISSUE THREAD

**Issue by Pascal76** [mikepultz/netdns2#139]
Hello

FYI
Deprecated: Exception::__construct(): Passing null to parameter #1 ($message) of type string is deprecated in /XXX/lib_8.2/vendor/pear/net_dns2/Net/DNS2/Exception.php on line 64

**Comment by tru7** [comment]
Seeking for a php 8.2 compatible release on pear.php.net as Debian stable provides php 8.2 and current version 1.5 lacks compatibility.

**Comment by viceice** [comment]
@mikepultz  please upload latest v1.5.3 to pear.php.net

**Comment by mikepultz** [comment]
The latest versions of 1.5.x are PHP 8.2 compatible, and can be installed via composer.

As far as PEAR- the package builder tools (PEAR_PackageFileManager2) seem to be broken and don't work with 7.4 or newer- so I don't really have a good way to build a current PEAR package, and I don't really have any time to fix their packages.

` PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /usr/share/pear/PEAR/PackageFileManager2.php on line 508`

So- unless they fix their packages, I will no longer be putting out PEAR packages.

Mike
