### ISSUE TITLE
Deprecate PHP version before 7.4

### ISSUE THREAD

**Issue by arnowelzel** [mikepultz/netdns2#142]
The README still says "PHP 5.4+" as requirement. However PHP 5.4 is way outdated and even PHP 7.4 is end of life:

https://www.php.net/supported-versions.php

Since even PHP 8.0 is already in its "Security fixes only" you should consider dropping support for PHP versions older than 7.4. This would make it much easier to use modern language elements of PHP like the null coalescing operator, anonymous classes etc.. Also see https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

**Comment by mikepultz** [comment]
The 1.5.x branch is going to stay as PHP 5.4+; 1.6.x will be newer.

Mike

**Comment by arnowelzel** [comment]
Some questions here:

- is the master branch not the newest version (1.6.x)?
- at the moment https://github.com/mikepultz/netdns2/blob/version-1.6.x/README.md also says "PHP 5.4+". Is an update to newer versions planned for the future versions?

**Comment by mikepultz** [comment]
Neither the master branch nor the 1.6.x branch are up-to-date; once I have a version that isn't broken, I'm going to commit to 1.6.x and merge into master, but I didn't want to do that until it was at least syntactically valid.

Currently, the only valid version is out of the 1.5.x branch.

Mike
