### ISSUE TITLE
Update packagist repository

### ISSUE THREAD

**Issue by tabacco** [mikepultz/netdns2#31]
The packagist record for this project still points at Google Code, and so doesn't have any of the tags from this repo: https://packagist.org/packages/pear/net_dns2

**Comment by mikepultz** [comment]
Yup- fixed.

**Comment by tabacco** [comment]
Thanks! Any chance you can also force an update (via the button on that page) to make it fetch the tags and such?

**Comment by mikepultz** [comment]
Yup- I did- I set up the auto-update hook thing at the same time too,

Mike
