### ISSUE TITLE
Tagged releases aren't making it into packagist's database

### ISSUE THREAD

**Issue by tabacco** [mikepultz/netdns2#33]
Looks like tagged releases aren't reflected by packagist: https://packagist.org/packages/pear/net_dns2

This makes it hard to use Net_DNS2 with composer.

**Comment by mikepultz** [comment]
Thanks-

It looks like it was just the naming convention that I was using before I moved things over from Google Code- packagist wasn't picking it up.

I've gone back and renamed all the tags- it looks like they've being picked up now.

Mike

**Comment by tabacco** [comment]
Thanks!
