### ISSUE TITLE
Version 1.3.2 is missed

### ISSUE THREAD

**Issue by DarioSwain** [mikepultz/netdns2#36]
Hi @mikepultz,

I can't find 1.3.2 version of netdns2. Seems like it missing.
Could you please release this version on GitHub?

**Comment by mikepultz** [comment]
Hey Ilya,

I don't actually have a full tag for this release; this was right around the time I moved things from Google code to Github, and there were a few things that didn't import over properly.

I have PHP PEAR package for this version if you'd like it though? it's only missing a few files (like the composer file, and README and package files.

Let me know, and I can send you a link.

Mike

**Comment by DarioSwain** [comment]
@mikepultz yes, I know, but it is a problem, I need to get this package via composer.

I make some investigation... Seems like this is [release commit for 1.3.2 version](https://github.com/mikepultz/netdns2/commit/18efb9396499157452b7f408fbe02edf0e7862fe).
In file ```Net/DNS2.php``` version changed to ```const VERSION = '1.3.2';```.
Realize dates are same for PEAR and GitHUb commits.

At now I can't use PEAR package with composer, because it is extremely slow for composer performance.

**Comment by mikepultz** [comment]
Ok, you should see a 1.3.2 release there now.

Mike

**Comment by DarioSwain** [comment]
@mikepultz  many thanks!
