### ISSUE TITLE
Net_DNS2 may fail to parse records if mbstring.func_overload is active for string functions

### ISSUE THREAD

**Issue by bishopb** [mikepultz/netdns2#41]
When the PHP INI settings have [function overloading](http://php.net/manual/en/mbstring.overload.php) enabled, Net_DNS2 may no longer have byte-level access to strings and users may receive bogus Parse errors or infinite loops.  For example, on my test machine, `tests/Net_DNS2_ParserTest.php` enters an infinite loop and crashes after memory exhaustion.

The README should mention that some values of this INI setting are incompatible with Net_DNS2. Run-time checks seem like unnecessary overhead, but there may be an argument in favor of that.

---- 

Note that Net_DNS2 is not the only package afflicted by this setting.  For example, [Symfony has a similar issue](https://github.com/sensiolabs/SensioDistributionBundle/pull/174).

**Comment by mikepultz** [comment]
Thanks! I've merged the changes in,

Mike
