### ISSUE TITLE
Signature verification API

### ISSUE THREAD

**Issue by bishopb** [mikepultz/netdns2#43]
Is there interest in an API to verify signatures, like [`dig +sigchase`](http://backreference.org/2010/11/17/dnssec-verification-with-dig/)?

It's easily implemented using the existing record infrastructure, but it's not clear to me where that API would best fit.  Ideas to open the conversation.

```
// always verify signatures
// Note 1: all these API changes imply setting $resolver->dnssec = true;
// Note 2: signature verification uses BOTTOM_UP as default
$resolver = new \Net_DNS2_Resolver();
$resolver->setSignatureVerification(\Net_DNS2_Resolver::TOP_DOWN); // also available BOTTOM_UP

// optionally, add in root keys? If not given, a TLD DNSKEY call will be made
// necessary to support islands of security?
// Note 1: Maybe the root keys should be an argument to {set,with}SignatureVerification()
$resolver->setRootKeys(array (  'ABCDEF...' ));

// or per-query
try {
    $resolver
        ->withRootKeys(array ('ABCDEF...')) // optional
        ->withSignatureVerification() // can also supply TOP_DOWN or BOTTOM_UP
        ->query('example.com', 'SSHFP')
    ;
} catch (\Net_DNS2_Exception_SignatureInvalid $ex) {
}
```

Perhaps an exception isn't a good idea. Maybe the answer should instead have a flag indicating the result?

Oh, and would the same API suffice for authenticated denial of existence, (ie [NSEC3](https://tools.ietf.org/html/rfc5155))?

See also [RFC 4035 &sect; 5](http://tools.ietf.org/html/rfc4035#section-5).

**Comment by mikepultz** [comment]
Hey Bishop,

I think it's a good idea- it's been on my TODO list for a long time- I just haven't had a chance to dig into it.

I think something like:

`$r->setSignatureVerification($method = BOTTOM_UP, $root_keys = '/etc/trusted-key.key');`

(or something like that)

would be better; that would mirror how authentication works right now (with `::signTSIG()` and `::signSIG0()`)- vs recursive methods- I don't have anything like that in the class right now I don't think.

As far as exceptions- I can see two options: if it's as-above, then it shouldn't throw an exception- simply return the results, and let devs decide what to do with them on their own- that's generally my preferred thinking.

or- change the feature to `$resolver->requireValidSignature(..);`, in which case, it throws an exception in the event it's invalid.

But I think the former (no exception); when dig fails a validation, it will give an error about the validation, but it still returns the A record data successfully- which I think makes sense.

Let me know what you think,

Mike

**Comment by bishopb** [comment]
Having dug through the existing code some more, and digested the contents of [RFC 4035 &sect; 5][1], I think the Net_DNS2 API should be as follows:

```
$resolver = new \Net_DNS2_Resolver();
$resolver->enableSignatureValidation();
try {
    $resolver->query('example.com', 'SSHFP');
} catch (\Net_DNS2_Exception_InvalidSignature $ex) {
     die($ex->getCode() . PHP_EOL . $ex->getMessage());
}
```

Which behaves as follow:

1. Tells the resolver that it is to become stringent about checking signatures
  1. Implies `dnssec = false` and `dnssec_cd_flag = false`
  2. Defaults to downloading a root key from `.`
    * The user can provide their own root keys file
    * Must be in zone file format, eg: `dig . DNSKEY | grep -Ev '^($|;)' > trusted.keys`
    * We don't verify the keys we download, [assumed they are secure][3]
2. Throws an exception per the `SHOULD` in &sect; 5.5
3. The only verification algorithm we implement is bottom-up
  1. We don't give the user a choice (there is no need to)

If an invalid signature is found, the output might look like the following:

```
102
DNSKEY 15141 does not validate RRset 'SSHFP' for example.com. Signer's name does not match zone in RRset.
```

The exception code corresponds to the specific failure bullet from RFC 4035 &sect; 5.2, 5.3.1, while the second sentence in the message corresponds to an English description of that code.

Validation happens after the answers are fetched, so it's possible -- though unadvisable -- for a consumer to continue using the RRSet after handling the signature failed exception.

Preliminary implementation in my [signature-validation branch][2]. Notes on this implementation as I think about them:

* If validation is requested, passes, and there is a resolver cache, then the answer is cached

[1]: http://tools.ietf.org/html/rfc4035#section-5
[2]: https://github.com/bishopb/netdns2/tree/signature-validation
[3]: https://www.cloudflare.com/dnssec/root-signing-ceremony/

**Comment by mikepultz** [comment]
Hey @bishopb,

Yup- I'm good with all of that- the only thing I would say, is that it shouldn't use a different exception; I made a point in the rest of the code, to only ever throw a Net_DNS2_Exception object, and use defined error codes in the Net_DNS2_Lookups class.

But I'm good with the rest of that,

Mike
