### ISSUE TITLE
PHPUnit required to run tests

### ISSUE THREAD

**Issue by bishopb** [mikepultz/netdns2#44]
The tests use PHPUnit, but neither the [local documentation][1], the [remote documentation][2], nor the `composer.json` file describe this dependency or how to install PHPUnit to run tests.  Sure, getting PHPUnit is trivial if you already know it, and arguably those using a DNS resolver already know how, but for completeness sake, the package should document how to test itself.

[1]: https://github.com/mikepultz/netdns2/blob/master/README.md
[2]: https://netdns2.com/documentation/

**Comment by mikepultz** [comment]
Hey @bishopb,

Sure- originally the PHPUnit code was used through PEAR, but i'm not sure when that changed or stopped working, so I've just been using it to validate the code on my side- but I'm good with opening it up so people can test on their owne.

Mike

**Comment by mikepultz** [comment]
These tests will be included in the next major release.

Mike
