### ISSUE TITLE
Support a loggable interface

### ISSUE THREAD

**Issue by bishopb** [mikepultz/netdns2#46]
DNS query tools like `dig` provide a trace option that shows exactly what the resolver is doing. While many simple queries don't benefit too much from traces, recursive queries do. For example, validating a signature requires many sub-queries and it'd be helpful to see the full trace for diagnostics.

The recommend logging mechanism for PHP is defined in [PSR-3][1], which has a [reference interface implementation][2].  However, the reference version requires PHP 5.3+, while the Net_DNS2 package requires 5.1.2+.  Since 5.1.2 was [released 10 years ago][1], and it's not a good use of time reinventing wheels, and generally since it's becoming increasingly difficult to rely on modern libraries because of this low requirement, it seems reasonable to require 5.3+ for all consumers.  Such a requirement would need to bump the library API to version 2, as it breaks BC.

[1]: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md
[2]: https://github.com/php-fig/log
[3]: https://secure.php.net/releases/#5.1.2

**Comment by mikepultz** [comment]
Do you have any examples of libraries that are actually using PSR-3?

I know the "spec" has been around for years, but I have yet to see anybody using it (in a library)?

On the PHP verison- I've been working on some other changes that would likely require a newer version of PHP, so I was going to jump to v2.0- so I have no problem with that.

MIke

**Comment by bishopb** [comment]
Sure, this is just a sample:

* https://github.com/authbucket/oauth2-php
* https://github.com/guzzle/guzzle
* https://github.com/symfony/http-kernel
* https://github.com/elastic/elasticsearch-php

There are at least [1674 packages that depend upon psr/log](https://www.versioneye.com/php/psr:log/references).

**Comment by mikepultz** [comment]
At this point, i'm not sure that adding additional code for logging will add any value to the code base. 

Nobody has asked for this feature, and I've polled some people that I know that use Net_DNS2 in some big projects, and I haven't found any interest for this feature. So I don't see the value in added the extra code to the code base.

If there's interest that develops, I would probably add it as a separate logging class, so it's not part of the main library.

Mike
