### ISSUE TITLE
IETF RFC 7929 DANE-OpenPGP released yesterday

### ISSUE THREAD

**Issue by renne** [mikepultz/netdns2#52]
Hi,

The [IETF RFC 7929 - DNS-Based Authentication of Named Entities (DANE) Bindings for OpenPGP](https://tools.ietf.org/html/rfc7929) has been released yesterday.

This allows DNSSEC-secured look-ups of public OpenPGP-keys with Net_DNS2. ;-)

@mikepultz Please check for changes in the final document and add a code example for OpenPGP-key look-ups at https://netdns2.com/documentation/examples/.

**Comment by mikepultz** [comment]
Hey @renne,

Support for the OPENPGPKEY resource record was added in v1.4.0- I added it based on the the RFC draft. It doesn't look like the wire format has changed in any way, so should work fine.

Mike
