### ISSUE TITLE
Example code for OpenPGP-lookup

### ISSUE THREAD

**Issue by renne** [mikepultz/netdns2#53]
@mikepultz 

Hi,

I'm going to do some IETF RFC7929-lobbying at webmail vendors (Owncloud email plugin, Rainloop, Roundcube, Mailvelope key server, etc.). Can you please add an code example how to lookup an OpenPGP-RR for an email address to [your NetDNS2 examples](https://netdns2.com/documentation/examples/) I can refer to?

This would speed up the deployment of email end-to-end-encryption a lot. ;)

**Comment by mikepultz** [comment]
Hey Renne,

Sure- https://netdns2.com/documentation/examples/#Lookup_OpenPGPKey_Record

This *should* work (according to the RFC)- unfortunately, I don't have a DNS server that properly supports the OPENPGPKEY type yet, but I think this is right.

Mike

**Comment by renne** [comment]
The german email providers [Core Networks](https://www.core-networks.de/), [mail.de](https://mail.de) and [Posteo](https://posteo.de/) already publish OpenPGPkey-records. If you want to test your [Net_DNS2](https://netdns2.com/) implementation you can look up the email-addresses info@core-networks.de, support@mail.de and support@posteo.de with [Net_DNS2](https://netdns2.com/). The result can be compared at [OPENPGPKEY.info](https://openpgpkey.info/)

Please add the `include '/usr/share/php/Net/DNS2.php';` statement and a description how to enable DNSSEC. ;-)

Issues have been posted at [Baikal](https://github.com/fruux/Baikal/issues/581), [Owncloud Contacts](https://github.com/owncloud/contacts/issues/490), [Rainloop](https://github.com/RainLoop/rainloop-webmail/issues/1116) and [Roundcube Webmailer](https://github.com/roundcube/roundcubemail/issues/5407).

**Comment by mikepultz** [comment]
Hey Renne,

Most implementations will use an auto-loader- so you don't need to specifically include() any of the libraries- none of the examples (from what I remember) specify an include, as to not create any confusion. Not all libraries will be installed under /usr/share/php/.

I added a line turning on DNSSEC- and I spot checked it on two of those addresses you sent and they both worked fine, and matched up with what BIND returns- so it should be good.

Mike
