### ISSUE TITLE
PSR-4 autoloading

### ISSUE THREAD

**Issue by Orgoth** [mikepultz/netdns2#55]
greetings
i changed the structure to psr-4.

Orgoth/netdns2@b871ef06e31f3900bf6cf55a084c79834dd8f66f

you don't need a separate autoloader anymore.
when someone adds your package to his composer, the autoload will be done by the composer.

I have also merge the pull request from bishop
Orgoth/netdns2@ef390225976884ac3073dc56d4b026426243cb93

if you are interessted, you are welcome
if not, close the ticket

**Comment by mikepultz** [comment]
Sorry, I can't merge in a change that renames all the classes, and exceptions- it's much too big of change.

Mike

**Comment by Orgoth** [comment]
hello mike,

no problem, i will keep track of your changes and merge them.  
So there are both versions available.

i will also create a additional pakagist package and change the readme to reflect the difference.

good day
Orgoth

**Comment by mikepultz** [comment]
Sounds good,

 

Mike
