### ISSUE TITLE
uninitialized string offset: 0

### ISSUE THREAD

**Issue by Erwane** [mikepultz/netdns2#58]
when doing query :
```php
Resolver::query('fr', 'NS');
```
on NameServer : 198.41.0.4 (one of root servers)

with no cache or removing cache file before
```php
Uninitialized string offset: 0

vendor/pear/net_dns2/Net/DNS2/Socket/Streams.php:309
vendor/pear/net_dns2/Net/DNS2.php:1198
vendor/pear/net_dns2/Net/DNS2.php:912
vendor/pear/net_dns2/Net/DNS2/Resolver.php:211
```

Version 1.4.0, 1.4.1, 1.4.2
Working fine on 1.3.2 or 1.2.5

thanks

**Comment by mikepultz** [comment]
Hey @Erwane,

I haven't been able to reproduce this on my development system; can you provide a working example that shows this issue? and I can try it on my side.

Thanks,

Mike

**Comment by Erwane** [comment]
can't reproduce :( Sorry.
