### ISSUE TITLE
CAA requests turn into A requests?

### ISSUE THREAD

**Issue by Synchro** [mikepultz/netdns2#60]
I'm trying to test some DNS settings related to CAA records, and it's proving unnecessarily difficult! net_dns2 is the only tool I've found so far that supports CAA-type lookups, but I can't persuade it to do them. For example:

```php
<?php
require 'vendor/autoload.php';

$r = new Net_DNS2_Resolver(array('nameservers' => array('8.8.8.8')));

$domain = 'google.com';

try {
    $result = $r->query($domain, 'CAA');
} catch (Net_DNS2_Exception $e) {

    echo "::query() failed: ", $e->getMessage(), "\n";
}

var_dump($result);
```

The question that submits is apparently:

```
  public $question =>
  array(1) {
    [0] =>
    class Net_DNS2_Question#9 (3) {
      public $qname =>
      string(10) "google.com"
      public $qtype =>
      string(1) "A"
      public $qclass =>
      string(2) "IN"
    }
  }
```

and so, not surprisingly, I get an A-type answer:

```
  public $answer =>
  array(8) {
    [0] =>
    class Net_DNS2_RR_A#10 (7) {
      public $address =>
      string(14) "77.154.227.249"
      public $name =>
      string(10) "google.com"
      public $type =>
      string(1) "A"
      public $class =>
      string(2) "IN"
...
```

Why is it not asking a CAA question? I have a slight chicken-and-egg problem - I don't know if this domain (or any other) *has* a CAA record, but I don't have any other tools to check whether it does (pointers welcome)! Regardless, I don't see why this is converted into a A question - if it defaults to that if a CAA lookup fails, I'd like it not to - I'm *only* interested in the CAA response, and I'd be happy to get an error if there is no such record.

**Comment by mikepultz** [comment]
Hey @Synchro,

Looks like you found a bug- the reason it's returning an A rather than a CAA, is because of a bit shifting issue on the Question object. The numerical ID for CAA is 257, and A is 1; because of the bitshift bug, it was rolling over the next 8 bit integer- 257 - 255 (the max allowed in an 8 bit int) = 1.

I've found and fixed the issue- i'll submit in a little while- in the meantime, if you want to fix you copy of NetDNS2, you can update the file:

```
Net_DNS2/Net/DNS2/Question.php
```

At the bottom of the file, replace the line:
```
$data .= chr($type << 8) . chr($type) . chr($class << 8) . chr($class);
```
with
```
$data .= chr($type >> 8) . chr($type) . chr($class >> 8) . chr($class);
```

With that change, I get this response (google.com does have a CAA record BTW)
```
  ["question"]=>
  array(1) {
    [0]=>
    object(Net_DNS2_Question)#8 (3) {
      ["qname"]=>
      string(10) "google.com"
      ["qtype"]=>
      string(3) "CAA"
      ["qclass"]=>
      string(2) "IN"
    }
  }
  ["answer"]=>
  array(1) {
    [0]=>
    object(Net_DNS2_RR_CAA)#9 (9) {
      ["flags"]=>
      int(0)
      ["tag"]=>
      string(5) "issue"
      ["value"]=>
      string(12) "symantec.com"
      ["name"]=>
      string(10) "google.com"
      ["type"]=>
      string(3) "CAA"
      ["class"]=>
      string(2) "IN"
      ["ttl"]=>
      int(84712)
      ["rdlength"]=>
      int(19)
      ["rdata"]=>
      string(19) "issuesymantec.com"
    }
  }
```

**Comment by Synchro** [comment]
Great, thanks for the fix! I guess "not many" people are using CAA lookups! BTW the reason I need this is I'm writing a PR to add CAA lookups to PHP's `dns_get_record` function and needed something to compare and test against.

**Comment by mikepultz** [comment]
No problem at all- there are only three RR's above 255, so I guess they must not be that popular!

Good luck with your build,

Mike
