### ISSUE TITLE
"invalid header: the request and response id do not match

### ISSUE THREAD

**Issue by Pascal76** [mikepultz/netdns2#61]
I got a lot of "invalid header: the request and response id do not match" errors
Sometime all is ok ... sometime: lot of errors... I don't known why.

more info:
https://github.com/PowerDNS/pdns/issues/4582#issuecomment-255270365

**Comment by mikepultz** [comment]
This is fixed in trunk, and will be included in the next release.

**Comment by dol** [comment]
@mikepultz Could you point out what the fix was. We currently encounter the same issue with 1.4.4.

**Comment by mikepultz** [comment]
Hey @dol -

I honestly can't remember what the change was; do you have some example code that generates the error?

Mike
