### ISSUE TITLE
Listing possible response attributes

### ISSUE THREAD

**Issue by moth** [mikepultz/netdns2#66]
Firstly, just a word of my appreciation for the work that's gone into this. It's made my life a lot easier, so thank you.

I have a question around expected responses, and if it's possible or not to ascertain a whitelist of known keys in the response arrays, eg; nsdname, name, type, ttl, rdata and so on.

The reason is that I need to transpose those to database columns, and I wondered if there is a manner in which to generate that list. Of course I could create them on the fly, but I'm trying to avoid that.

**Comment by mikepultz** [comment]
Hey @moth,

So the key names for all the variables are local properties on the various resource record classes- so everything under:

Net/DNS2/RR/*

The variable names (for the most part) were chosen to match the names defined in the RDATA sections of the resource type, that I pulled from the various RFC's.

For example, RFC 1035 (the original DNS RFC) - https://www.ietf.org/rfc/rfc1035.txt

If you look at section 3.3, you'll see the various RDATA formats for the different resource record types (CNAME, HINFO, etc.)- those names "CNAME", "CPU", "OS", etc. are the names that I used in the classes.

Some of the properties will be the same on each, extended from the RR.php class- for example, rdata, rdlength, ttl, class, type, and name will be there on each; anything else will be for that specific RR type.

You could probably generate that list by looping through each RR class, create an empty instance of it, and then use something like get_object_vars() to get a list of them?

I guess it would depend on how many different resource records you wanted to support? if you're just doing SOA/NS/A/CNAME/MX/TXT- it's going to be a short list.

Hopefully that helps!

Mike

**Comment by moth** [comment]
Great, thanks - that set me on the right track;

```
aa
address
afi
algorithm
altitude
apl_items
area
bitmap
cert_format_id_to_name
cert_format_name_to_id
cert_usage
certificate
class
cname
cpu
dfi
digest
digest_type
digesttype
dname
do
error
exchange
expiration
expire
extended_rcode
fingerprint
flags
format
fp_type
fqdn
fudge
gateway
gateway_type
hash_length
hashed_owner_name
hit
hit_length
horiz_pre
hostname
id
id_type
idi
inception
intermediatehost
isdnaddress
iterations
key
key_data
key_size
keytag
labels
latitude
locator32
locator64
longitude
mac
mac_size
map822
mapx400
matching_type
mboxdname
minimum
mname
mode
name
next
next_domain_name
nodeid
nsdname
option_code
option_data
option_length
order
original_id
origttl
os
other_data
other_length
other_size
pk_algorithm
pk_length
port
precedence
preference
previous
priority
private_key
protocol
psdnaddress
ptrdname
public_key
rd
rdata
rdlength
refresh
regexp
rendezvous_servers
replacement
retry
rname
rsvd
sa
salt
salt_length
sel
selector
serial
services
sigexp
sigincep
signature
signname
size
subtype
tag
target
text
time_signed
tsgi_mode_id_to_name
ttl
txtdname
type
type_bit_maps
typecovered
value
version
vert_pre
weight
z
```
