### ISSUE TITLE
blacklist usage

### ISSUE THREAD

**Issue by doublex** [mikepultz/netdns2#67]
This example throws an error. Expected result: "127.0.1.106"

````
<?php
require_once 'Net/DNS2.php';
$resolver = new Net_DNS2_Resolver();
$resolver->timeout = 1;
$response = 0;
try
{
    $response = $resolver->query("asd.ru.dbl.spamhaus.org", "A");
}
catch(Net_DNS2_Exception $e)
{
    die( "Exception\n" );
}
foreach ($response->answer as $rrr)
    echo $rrr->address."\n";
````

**Comment by mikepultz** [comment]
hey @doublex 

What's the exception that's being thrown? can you dump $e?

Are you sure it's just not timing out? 1 second isn't a lot of time for some RBLs- I've seen the spamhaus lists take 4-5 seconds to respond sometimes.

Mike

**Comment by doublex** [comment]
My fault - the nameserver "8.8.8.8" is blocked by "dbl.spamhaus.org".

The exception is:
"Net_DNS2_Exception: DNS request failed: The domain name referenced in the query does not exist. in /tmp/test-dns/Net_DNS2-1.4.3/Net/DNS2.php:1035"

Question: Is there a chance to resolve the DNS without asking a nameserver (direct lookup)?
Thanks a lot!

**Comment by mikepultz** [comment]
Sure- just do a NS lookup on dbl.spamhaus.org first; that'll give you a list of their authoritative name servers; then just grab one or two of those, and use them to do a direct lookup- straight from the source.

Mike

**Comment by doublex** [comment]
Thanks a lot.
Sorry for disturbing.
