### ISSUE TITLE
Option to decompress names in rdata

### ISSUE THREAD

**Issue by BenBE** [mikepultz/netdns2#73]
DNS requests and responses can use name compression in labels. While this saves bandwidth on the wire it makes individual RRs dependent on the raw response object and thus hard to store into a database.

It would be nice if there was a method to request the response object with the label compression undone.

E.g. given a response for the query
. IN NS
and answer RRs starting at offset 20h:
. 518400 IN NS a.root-servers.net.
00 0007E900 0001 0002 0014 01 61 0C 726F6F742D73657276657273 03 6E6574 00
. 518400 IN NS b.root-servers.net.
00 0007E900 0001 0002 0004 01 62 C0 2D
it would be nice if all returned records could be brought into their uncompressed form (like incidentially the first one is already).

**Comment by mikepultz** [comment]
The rdata value is already included as part of the answer object; that data could simply be stored as-is, and unpacked as needed.

Storing the individual rdata values for each RR doesn't really make sense to me, given that each one is going to rely on the previous RR values (given how the DNS compression works), to be unpacked. If you stored the values individually in a database, then you'd always have to select several, if not all of them (depending on your naming conventions) to unpack a single entry- in that case, it's probably cheaper just to store the answer rdata.

But if you had a specific use-case in mind, feel free to submit a pull request and I'll take a look.

Mike

**Comment by BenBE** [comment]
I have a usecase (basically: monitoring DNS zones over time) where I do minimal post-processing to get individual RRs into the DB (some, but not all, as I e.g. don't need the RRSIGs from DNSSEC once verified). When later comparing it's easiest, if all records' rdata were in canonical (uncompressed) form, as this makes records order-independent.

Will need to see, if I find a good way to do the decompression without too much overhead.
(Shouldn't you have source for something similar for DNSSEC validation?)

**Comment by mikepultz** [comment]
The DNS library doesn't do DNSSEC validation- it's just a resolver library.

This patch doesn't really do anything- i'll leave this thread open in the event you want to add more to it.

Mike
