### ISSUE TITLE
Allow DNSKEY export to canonical PKCS#7 format

### ISSUE THREAD

**Issue by BenBE** [mikepultz/netdns2#75]
The wire format of DNSSEC heavily varies from commonly used cryptographic key containers that use the SPKI (Subject Public Key Information) structure present in e.g. X.509 certificates. Having some utility functions to convert the DNS wire format to e.g. PKCS#7 would be good.

**Comment by mikepultz** [comment]
I don't think the DNS library should be formatting output in different ways- it's simply a lookup library, formatting should be done outside of this library.
