### ISSUE TITLE
Provide option to ignore server returning errors

### ISSUE THREAD

**Issue by BenBE** [mikepultz/netdns2#76]
Sometimes you need to query for some records that aren't available at the server. While this gives an error of NODATA or SERVFAIL the library should not block you from obtaining the full server's response in such cases too.

Thus in Net_DNS2_Resolver::query the check for a NOERROR response should be made optional if recursion is disabled (AND some option to return error results is set).

P.S.: Yes, one application of this is e.g. zone walking.

**Comment by mikepultz** [comment]
This isn't needed.

Both the request and response objects are included in the instance of the Net_DNS2_Exception thrown with the error. This lets you obtain the full response in the event of a failure, while still preserving the expectation of getting an exception on an error.

Mike
