### ISSUE TITLE
Deprecated each() in PHP7.2

### ISSUE THREAD

**Issue by Deadooshka** [mikepultz/netdns2#79]
``````
PHP Deprecated:  The each() function is deprecated.
This message will be suppressed on further calls in ...\DNS2.php on line 923
``````
consider using `$ns = current($this->nameservers); next($this->nameservers);` and removing `$ns = $ns[1];`.

**Comment by mikepultz** [comment]
Thanks @Deadooshka - I'll take a look a refactoring this code for the next release.

Mike

**Comment by mikepultz** [comment]
This will be fixed in the next release.

Mike

**Comment by strebl** [comment]
@mikepultz Hi Mike, do you have plans when the next release will be?

**Comment by mikepultz** [comment]
hey @strebl - possibly this weekend if I can find a few hours to fix one last bug.

I'll keep you posted,

Mike

**Comment by strebl** [comment]
Nice, thanks @mikepultz!

**Comment by mikepultz** [comment]
They @strebl- this was just released.

Mike

**Comment by strebl** [comment]
Thanks @mikepultz
