### ISSUE TITLE
Php 7.2 support

### ISSUE THREAD

**Issue by Belphemur** [mikepultz/netdns2#85]
Hello,

In PHP 7.2, `each()` has been deprecated.

Could you replace this code https://github.com/mikepultz/netdns2/blob/master/Net/DNS2.php#L918-L938 by foreach or do the same logic without each ?

Edit: I saw you have a pull request #84 to resolve this.
Edit2: Saw this commit on one of your fork that would keep the code quite the same:
https://github.com/aripringle/netdns2/commit/61cd0bf0fc0396848e8526da59dd2632aedffedb
Edit3: Duplicate #79

**Comment by mikepultz** [comment]
This was fixed in v1.4.4 (just released).

Mike

**Comment by Belphemur** [comment]
Thanks for this 👍
