### ISSUE TITLE
Wrong phpdoc return type for Net_DNS2_Resolver:query()

### ISSUE THREAD

**Issue by hluaces** [mikepultz/netdns2#92]
My IDE warned me about a type mismatch on some operations and I found out that `Net_DNS2_Resolver:query()` returns the response obtained from `Net_DNS2:sendPacket()` which happens to be a `Net_DNS2_Packet_Response` object, or `false` on error.

This makes the phpdoc on `Net_DNS2_Resolver:query()` incorrect, as it states that the method returns a `Net_DNS2_RR object` and thus raises the inspections warnings.

Not a big deal but reporting it nevertheless.

**Comment by mikepultz** [comment]
thanks @hluaces - I'll add it to my list!

Cheers,

Mike

**Comment by mikepultz** [comment]
fixed; will be in the next release.

Mike
