### ISSUE TITLE
Framework necessary?

### ISSUE THREAD

**Issue by DieselDriver** [mikepultz/netdns2#99]
Hi,

I downloaded and installed NetDNS2

**Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in ..../net_dns2/tests/Net_DNS2_ResolverTest.php on line 66**

Do you have any working example source?

The DNS2.php file works but I am not able to use this class for adding a new object.

Best

**Comment by mikepultz** [comment]
hey @DieselDriver,

You only need the PHPUnit framework if you want to run the automated test functions.

There are several example on the website:

https://netdns2.com/documentation/examples/

Mike
